### ISSUE TITLE
npm이나 nodejs의 버전 때문에 문제가 생길때.

### ISSUE THREAD

**Issue by petrosyh** [snu-sf-class/swpp201701#27]
```#``` 표시 뒤에 있는 것은 주석이니, 같이 복사하지 마세요

- nodejs 업데이트

node -v #nodejs 버전 확인하기
sudo npm cache clean -f #강제 캐시 삭제
sudo npm install -g n #n모듈 설치
sudo n stable #n모듈로 nodejs설치
node -v #다시 버전 확인

여기서 버전이 바뀌지 않았거나 에러가 발생한다면, 파일 링크를 직접 설정하세요.
(예를들면, 
sudo ln -sf /usr/local/n/versions/node/6.0.0/bin/node /usr/bin/node
)

- npm 업데이트

npm -v #버전 확인
sudo npm install -g npm #npm으로 npm설치
npm -v #버전 확인

**Comment by pokdong** [comment]
Npm 버전이 바뀌지 않고 계속 똑같으면 어떻게 해야하나요
